Services
lambdaclass/hacking_learning_path pull request #38
Opened 2022-01-12 19:06 UTC by alexislambda

Wil generate a new section for services and infrastructure

-Now added: Azure, Kubernetes, AWS

2022-01-14 19:40 UTC, gabrielbosio requested changes
Some

2022-01-14 19:40 UTC, gabrielbosio commented on README.md
> +### ASW
Fix typo: AWS

2022-01-14 19:40 UTC, gabrielbosio commented on README.md
> +### ASW tools
Fix typo: AWS tools

2022-01-14 19:40 UTC, gabrielbosio commented on README.md
> +To further learn about ASW and it's practical uses go [HERE](https://github.com/bregman-arie/devops-exercises/tree/master/exercises/aws) for exercises. (AWS - EC2/IAM/Containers)
Fix typo: To further learn about AWS

2022-01-14 19:40 UTC, gabrielbosio commented on README.md
> +- [Kubernete Basics](https://kubernetes.io/docs/tutorials/kubernetes-basics/)
Fix typo: Kubernetes Basics

2022-01-14 19:40 UTC, gabrielbosio commented on README.md
> +-[Azure FAQ]From devops-exercises repositories(https://github.com/bregman-arie/devops-exercises#azure)
Fix syntax:
Maybe this way: -[Azure FAQ](https://github.com/bregman-arie/devops-exercises#azure) From devops-exercises repositories
Or this way: -[Azure FAQ From devops-exercises repositories](https://github.com/bregman-arie/devops-exercises#azure)

2022-01-14 19:40 UTC, gabrielbosio commented on README.md
> +### Installing Erlang and Elixir
Maybe commands should be typed as monospace?
Example: `brew install erlang` or `brew install elixir`

2022-01-14 19:40 UTC, gabrielbosio commented on README.md
> +### Installing phoenix
Capitalize Phoenix word:
Installing Phoenix
For Phoenix all dependencies...

2022-01-16 00:32 UTC, unbalancedparentheses commented on README.md
> +### ASW
@alexislambda please fix it.

2022-01-16 00:32 UTC, unbalancedparentheses commented
@alexislambda please solve conflicts and update the typos

2022-01-17 15:43 UTC, alexislambda commented on README.md
> +### Installing Erlang and Elixir
done

2022-01-17 15:51 UTC, gabrielbosio commented on README.md
> +- On Mac distributions, you can just <!--*brew install erlang--> to get the latest installation. In case of needing an specific version you can use asdf and install with <!--asdf install erlang [VERS
I don't see the commands in the preview, maybe try with the character `

2022-01-17 15:52 UTC, gabrielbosio commented on README.md
> +-[Azure FAQ From devops-exercises repositories](https://github.com/bregman-arie/devops-exercises#azure)
Add a space after the hyphen (- [Azure FAQ...) to make the unordered list

2022-01-17 16:28 UTC, gabrielbosio approved these changes

2022-01-19 23:35 UTC, merged